// actions
const HEROES_FETCHING = 'HEROES_FETCHING';
const HEROES_FETCHED = 'HEROES_FETCHED';
const HEROES_FETCHING_ERROR = 'HEROES_FETCHING_ERROR';
const HERO_DELETED = 'HERO_DELETED';
const HEROES_CREATED = 'HEROES_CREATED';
const HEROES_CREATION = 'HEROES_CREATION';
const HEROES_CREATION_ERROR = 'HEROES_CREATION_ERROR';
const FILTERS_FETCHING = 'FILTERS_FETCHING';
const FILTERS_FETCHED = 'FILTERS_FETCHED';
const FILTERS_FETCHING_ERROR = 'FILTERS_FETCHING_ERROR';
const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';

// URL
const BASE_URL = 'https://a80cca7ab3fe2a8b.mokky.dev';

export {
  HEROES_FETCHING,
  HEROES_FETCHED,
  HEROES_FETCHING_ERROR,
  HERO_DELETED,
  BASE_URL,
  HEROES_CREATED,
  HEROES_CREATION,
  HEROES_CREATION_ERROR,
  FILTERS_FETCHING,
  FILTERS_FETCHED,
  FILTERS_FETCHING_ERROR,
  SET_ACTIVE_FILTER,
};
